/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CaminoRouteImport } from './routes/camino'
import { Route as CocodriloRouteImport } from './routes/cocodrilo'
import { Route as ConsonantesRouteImport } from './routes/consonantes'
import { Route as CuevaRouteImport } from './routes/cueva'
import { Route as EnglishRouteImport } from './routes/english'
import { Route as LenguajeRouteImport } from './routes/lenguaje'
import { Route as MatematicasRouteImport } from './routes/matematicas'
import { Route as OracionesRouteImport } from './routes/oraciones'
import { Route as PizzeriaRouteImport } from './routes/pizzeria'
import { Route as PremiosRouteImport } from './routes/premios'
import { Route as TorreRouteImport } from './routes/torre'
import { Route as TrazosRouteImport } from './routes/trazos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CaminoRoute = CaminoRouteImport.update({
  id: '/camino',
  path: '/camino',
  getParentRoute: () => rootRouteImport,
} as any)
const CocodriloRoute = CocodriloRouteImport.update({
  id: '/cocodrilo',
  path: '/cocodrilo',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsonantesRoute = ConsonantesRouteImport.update({
  id: '/consonantes',
  path: '/consonantes',
  getParentRoute: () => rootRouteImport,
} as any)
const CuevaRoute = CuevaRouteImport.update({
  id: '/cueva',
  path: '/cueva',
  getParentRoute: () => rootRouteImport,
} as any)
const EnglishRoute = EnglishRouteImport.update({
  id: '/english',
  path: '/english',
  getParentRoute: () => rootRouteImport,
} as any)
const LenguajeRoute = LenguajeRouteImport.update({
  id: '/lenguaje',
  path: '/lenguaje',
  getParentRoute: () => rootRouteImport,
} as any)
const MatematicasRoute = MatematicasRouteImport.update({
  id: '/matematicas',
  path: '/matematicas',
  getParentRoute: () => rootRouteImport,
} as any)
const OracionesRoute = OracionesRouteImport.update({
  id: '/oraciones',
  path: '/oraciones',
  getParentRoute: () => rootRouteImport,
} as any)
const PizzeriaRoute = PizzeriaRouteImport.update({
  id: '/pizzeria',
  path: '/pizzeria',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiosRoute = PremiosRouteImport.update({
  id: '/premios',
  path: '/premios',
  getParentRoute: () => rootRouteImport,
} as any)
const TorreRoute = TorreRouteImport.update({
  id: '/torre',
  path: '/torre',
  getParentRoute: () => rootRouteImport,
} as any)
const TrazosRoute = TrazosRouteImport.update({
  id: '/trazos',
  path: '/trazos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/camino': typeof CaminoRoute
  '/cocodrilo': typeof CocodriloRoute
  '/consonantes': typeof ConsonantesRoute
  '/cueva': typeof CuevaRoute
  '/english': typeof EnglishRoute
  '/lenguaje': typeof LenguajeRoute
  '/matematicas': typeof MatematicasRoute
  '/oraciones': typeof OracionesRoute
  '/pizzeria': typeof PizzeriaRoute
  '/premios': typeof PremiosRoute
  '/torre': typeof TorreRoute
  '/trazos': typeof TrazosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/camino': typeof CaminoRoute
  '/cocodrilo': typeof CocodriloRoute
  '/consonantes': typeof ConsonantesRoute
  '/cueva': typeof CuevaRoute
  '/english': typeof EnglishRoute
  '/lenguaje': typeof LenguajeRoute
  '/matematicas': typeof MatematicasRoute
  '/oraciones': typeof OracionesRoute
  '/pizzeria': typeof PizzeriaRoute
  '/premios': typeof PremiosRoute
  '/torre': typeof TorreRoute
  '/trazos': typeof TrazosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/camino': typeof CaminoRoute
  '/cocodrilo': typeof CocodriloRoute
  '/consonantes': typeof ConsonantesRoute
  '/cueva': typeof CuevaRoute
  '/english': typeof EnglishRoute
  '/lenguaje': typeof LenguajeRoute
  '/matematicas': typeof MatematicasRoute
  '/oraciones': typeof OracionesRoute
  '/pizzeria': typeof PizzeriaRoute
  '/premios': typeof PremiosRoute
  '/torre': typeof TorreRoute
  '/trazos': typeof TrazosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/camino'
    | '/cocodrilo'
    | '/consonantes'
    | '/cueva'
    | '/english'
    | '/lenguaje'
    | '/matematicas'
    | '/oraciones'
    | '/pizzeria'
    | '/premios'
    | '/torre'
    | '/trazos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/camino'
    | '/cocodrilo'
    | '/consonantes'
    | '/cueva'
    | '/english'
    | '/lenguaje'
    | '/matematicas'
    | '/oraciones'
    | '/pizzeria'
    | '/premios'
    | '/torre'
    | '/trazos'
  id:
    | '__root__'
    | '/'
    | '/camino'
    | '/cocodrilo'
    | '/consonantes'
    | '/cueva'
    | '/english'
    | '/lenguaje'
    | '/matematicas'
    | '/oraciones'
    | '/pizzeria'
    | '/premios'
    | '/torre'
    | '/trazos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CaminoRoute: typeof CaminoRoute
  CocodriloRoute: typeof CocodriloRoute
  ConsonantesRoute: typeof ConsonantesRoute
  CuevaRoute: typeof CuevaRoute
  EnglishRoute: typeof EnglishRoute
  LenguajeRoute: typeof LenguajeRoute
  MatematicasRoute: typeof MatematicasRoute
  OracionesRoute: typeof OracionesRoute
  PizzeriaRoute: typeof PizzeriaRoute
  PremiosRoute: typeof PremiosRoute
  TorreRoute: typeof TorreRoute
  TrazosRoute: typeof TrazosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camino': {
      id: '/camino'
      path: '/camino'
      fullPath: '/camino'
      preLoaderRoute: typeof CaminoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cocodrilo': {
      id: '/cocodrilo'
      path: '/cocodrilo'
      fullPath: '/cocodrilo'
      preLoaderRoute: typeof CocodriloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consonantes': {
      id: '/consonantes'
      path: '/consonantes'
      fullPath: '/consonantes'
      preLoaderRoute: typeof ConsonantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cueva': {
      id: '/cueva'
      path: '/cueva'
      fullPath: '/cueva'
      preLoaderRoute: typeof CuevaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/english': {
      id: '/english'
      path: '/english'
      fullPath: '/english'
      preLoaderRoute: typeof EnglishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lenguaje': {
      id: '/lenguaje'
      path: '/lenguaje'
      fullPath: '/lenguaje'
      preLoaderRoute: typeof LenguajeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matematicas': {
      id: '/matematicas'
      path: '/matematicas'
      fullPath: '/matematicas'
      preLoaderRoute: typeof MatematicasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oraciones': {
      id: '/oraciones'
      path: '/oraciones'
      fullPath: '/oraciones'
      preLoaderRoute: typeof OracionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pizzeria': {
      id: '/pizzeria'
      path: '/pizzeria'
      fullPath: '/pizzeria'
      preLoaderRoute: typeof PizzeriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premios': {
      id: '/premios'
      path: '/premios'
      fullPath: '/premios'
      preLoaderRoute: typeof PremiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/torre': {
      id: '/torre'
      path: '/torre'
      fullPath: '/torre'
      preLoaderRoute: typeof TorreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trazos': {
      id: '/trazos'
      path: '/trazos'
      fullPath: '/trazos'
      preLoaderRoute: typeof TrazosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CaminoRoute: CaminoRoute,
  CocodriloRoute: CocodriloRoute,
  ConsonantesRoute: ConsonantesRoute,
  CuevaRoute: CuevaRoute,
  EnglishRoute: EnglishRoute,
  LenguajeRoute: LenguajeRoute,
  MatematicasRoute: MatematicasRoute,
  OracionesRoute: OracionesRoute,
  PizzeriaRoute: PizzeriaRoute,
  PremiosRoute: PremiosRoute,
  TorreRoute: TorreRoute,
  TrazosRoute: TrazosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
