/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as CaminoRouteImport } from './routes/camino'
import { Route as CienciaRouteImport } from './routes/ciencia'
import { Route as CocodriloRouteImport } from './routes/cocodrilo'
import { Route as CommandsRouteImport } from './routes/commands'
import { Route as ConsonantesRouteImport } from './routes/consonantes'
import { Route as CuevaRouteImport } from './routes/cueva'
import { Route as CvcRouteImport } from './routes/cvc'
import { Route as EnergiaRouteImport } from './routes/energia'
import { Route as EnglishRouteImport } from './routes/english'
import { Route as EvaluacionRouteImport } from './routes/evaluacion'
import { Route as GuatemalaRouteImport } from './routes/guatemala'
import { Route as HuertoRouteImport } from './routes/huerto'
import { Route as InversasRouteImport } from './routes/inversas'
import { Route as LenguajeRouteImport } from './routes/lenguaje'
import { Route as MatematicasRouteImport } from './routes/matematicas'
import { Route as MonedaRouteImport } from './routes/moneda'
import { Route as Numeros100RouteImport } from './routes/numeros100'
import { Route as OracionesRouteImport } from './routes/oraciones'
import { Route as PhonicsRouteImport } from './routes/phonics'
import { Route as PizzeriaRouteImport } from './routes/pizzeria'
import { Route as PremiosRouteImport } from './routes/premios'
import { Route as ReservaRouteImport } from './routes/reserva'
import { Route as RestaurantRouteImport } from './routes/restaurant'
import { Route as RomanosRouteImport } from './routes/romanos'
import { Route as TecnicasRouteImport } from './routes/tecnicas'
import { Route as TorreRouteImport } from './routes/torre'
import { Route as TrazosRouteImport } from './routes/trazos'
import { Route as UniversoRouteImport } from './routes/universo'
import { Route as VocabularioRouteImport } from './routes/vocabulario'
import { Route as VowelsRouteImport } from './routes/vowels'
import { Route as ZooRouteImport } from './routes/zoo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const CaminoRoute = CaminoRouteImport.update({
  id: '/camino',
  path: '/camino',
  getParentRoute: () => rootRouteImport,
} as any)
const CienciaRoute = CienciaRouteImport.update({
  id: '/ciencia',
  path: '/ciencia',
  getParentRoute: () => rootRouteImport,
} as any)
const CocodriloRoute = CocodriloRouteImport.update({
  id: '/cocodrilo',
  path: '/cocodrilo',
  getParentRoute: () => rootRouteImport,
} as any)
const CommandsRoute = CommandsRouteImport.update({
  id: '/commands',
  path: '/commands',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsonantesRoute = ConsonantesRouteImport.update({
  id: '/consonantes',
  path: '/consonantes',
  getParentRoute: () => rootRouteImport,
} as any)
const CuevaRoute = CuevaRouteImport.update({
  id: '/cueva',
  path: '/cueva',
  getParentRoute: () => rootRouteImport,
} as any)
const CvcRoute = CvcRouteImport.update({
  id: '/cvc',
  path: '/cvc',
  getParentRoute: () => rootRouteImport,
} as any)
const EnergiaRoute = EnergiaRouteImport.update({
  id: '/energia',
  path: '/energia',
  getParentRoute: () => rootRouteImport,
} as any)
const EnglishRoute = EnglishRouteImport.update({
  id: '/english',
  path: '/english',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluacionRoute = EvaluacionRouteImport.update({
  id: '/evaluacion',
  path: '/evaluacion',
  getParentRoute: () => rootRouteImport,
} as any)
const GuatemalaRoute = GuatemalaRouteImport.update({
  id: '/guatemala',
  path: '/guatemala',
  getParentRoute: () => rootRouteImport,
} as any)
const HuertoRoute = HuertoRouteImport.update({
  id: '/huerto',
  path: '/huerto',
  getParentRoute: () => rootRouteImport,
} as any)
const InversasRoute = InversasRouteImport.update({
  id: '/inversas',
  path: '/inversas',
  getParentRoute: () => rootRouteImport,
} as any)
const LenguajeRoute = LenguajeRouteImport.update({
  id: '/lenguaje',
  path: '/lenguaje',
  getParentRoute: () => rootRouteImport,
} as any)
const MatematicasRoute = MatematicasRouteImport.update({
  id: '/matematicas',
  path: '/matematicas',
  getParentRoute: () => rootRouteImport,
} as any)
const MonedaRoute = MonedaRouteImport.update({
  id: '/moneda',
  path: '/moneda',
  getParentRoute: () => rootRouteImport,
} as any)
const Numeros100Route = Numeros100RouteImport.update({
  id: '/numeros100',
  path: '/numeros100',
  getParentRoute: () => rootRouteImport,
} as any)
const OracionesRoute = OracionesRouteImport.update({
  id: '/oraciones',
  path: '/oraciones',
  getParentRoute: () => rootRouteImport,
} as any)
const PhonicsRoute = PhonicsRouteImport.update({
  id: '/phonics',
  path: '/phonics',
  getParentRoute: () => rootRouteImport,
} as any)
const PizzeriaRoute = PizzeriaRouteImport.update({
  id: '/pizzeria',
  path: '/pizzeria',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiosRoute = PremiosRouteImport.update({
  id: '/premios',
  path: '/premios',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservaRoute = ReservaRouteImport.update({
  id: '/reserva',
  path: '/reserva',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurantRoute = RestaurantRouteImport.update({
  id: '/restaurant',
  path: '/restaurant',
  getParentRoute: () => rootRouteImport,
} as any)
const RomanosRoute = RomanosRouteImport.update({
  id: '/romanos',
  path: '/romanos',
  getParentRoute: () => rootRouteImport,
} as any)
const TecnicasRoute = TecnicasRouteImport.update({
  id: '/tecnicas',
  path: '/tecnicas',
  getParentRoute: () => rootRouteImport,
} as any)
const TorreRoute = TorreRouteImport.update({
  id: '/torre',
  path: '/torre',
  getParentRoute: () => rootRouteImport,
} as any)
const TrazosRoute = TrazosRouteImport.update({
  id: '/trazos',
  path: '/trazos',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversoRoute = UniversoRouteImport.update({
  id: '/universo',
  path: '/universo',
  getParentRoute: () => rootRouteImport,
} as any)
const VocabularioRoute = VocabularioRouteImport.update({
  id: '/vocabulario',
  path: '/vocabulario',
  getParentRoute: () => rootRouteImport,
} as any)
const VowelsRoute = VowelsRouteImport.update({
  id: '/vowels',
  path: '/vowels',
  getParentRoute: () => rootRouteImport,
} as any)
const ZooRoute = ZooRouteImport.update({
  id: '/zoo',
  path: '/zoo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/camino': typeof CaminoRoute
  '/ciencia': typeof CienciaRoute
  '/cocodrilo': typeof CocodriloRoute
  '/commands': typeof CommandsRoute
  '/consonantes': typeof ConsonantesRoute
  '/cueva': typeof CuevaRoute
  '/cvc': typeof CvcRoute
  '/energia': typeof EnergiaRoute
  '/english': typeof EnglishRoute
  '/evaluacion': typeof EvaluacionRoute
  '/guatemala': typeof GuatemalaRoute
  '/huerto': typeof HuertoRoute
  '/inversas': typeof InversasRoute
  '/lenguaje': typeof LenguajeRoute
  '/matematicas': typeof MatematicasRoute
  '/moneda': typeof MonedaRoute
  '/numeros100': typeof Numeros100Route
  '/oraciones': typeof OracionesRoute
  '/phonics': typeof PhonicsRoute
  '/pizzeria': typeof PizzeriaRoute
  '/premios': typeof PremiosRoute
  '/reserva': typeof ReservaRoute
  '/restaurant': typeof RestaurantRoute
  '/romanos': typeof RomanosRoute
  '/tecnicas': typeof TecnicasRoute
  '/torre': typeof TorreRoute
  '/trazos': typeof TrazosRoute
  '/universo': typeof UniversoRoute
  '/vocabulario': typeof VocabularioRoute
  '/vowels': typeof VowelsRoute
  '/zoo': typeof ZooRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/camino': typeof CaminoRoute
  '/ciencia': typeof CienciaRoute
  '/cocodrilo': typeof CocodriloRoute
  '/commands': typeof CommandsRoute
  '/consonantes': typeof ConsonantesRoute
  '/cueva': typeof CuevaRoute
  '/cvc': typeof CvcRoute
  '/energia': typeof EnergiaRoute
  '/english': typeof EnglishRoute
  '/evaluacion': typeof EvaluacionRoute
  '/guatemala': typeof GuatemalaRoute
  '/huerto': typeof HuertoRoute
  '/inversas': typeof InversasRoute
  '/lenguaje': typeof LenguajeRoute
  '/matematicas': typeof MatematicasRoute
  '/moneda': typeof MonedaRoute
  '/numeros100': typeof Numeros100Route
  '/oraciones': typeof OracionesRoute
  '/phonics': typeof PhonicsRoute
  '/pizzeria': typeof PizzeriaRoute
  '/premios': typeof PremiosRoute
  '/reserva': typeof ReservaRoute
  '/restaurant': typeof RestaurantRoute
  '/romanos': typeof RomanosRoute
  '/tecnicas': typeof TecnicasRoute
  '/torre': typeof TorreRoute
  '/trazos': typeof TrazosRoute
  '/universo': typeof UniversoRoute
  '/vocabulario': typeof VocabularioRoute
  '/vowels': typeof VowelsRoute
  '/zoo': typeof ZooRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/camino': typeof CaminoRoute
  '/ciencia': typeof CienciaRoute
  '/cocodrilo': typeof CocodriloRoute
  '/commands': typeof CommandsRoute
  '/consonantes': typeof ConsonantesRoute
  '/cueva': typeof CuevaRoute
  '/cvc': typeof CvcRoute
  '/energia': typeof EnergiaRoute
  '/english': typeof EnglishRoute
  '/evaluacion': typeof EvaluacionRoute
  '/guatemala': typeof GuatemalaRoute
  '/huerto': typeof HuertoRoute
  '/inversas': typeof InversasRoute
  '/lenguaje': typeof LenguajeRoute
  '/matematicas': typeof MatematicasRoute
  '/moneda': typeof MonedaRoute
  '/numeros100': typeof Numeros100Route
  '/oraciones': typeof OracionesRoute
  '/phonics': typeof PhonicsRoute
  '/pizzeria': typeof PizzeriaRoute
  '/premios': typeof PremiosRoute
  '/reserva': typeof ReservaRoute
  '/restaurant': typeof RestaurantRoute
  '/romanos': typeof RomanosRoute
  '/tecnicas': typeof TecnicasRoute
  '/torre': typeof TorreRoute
  '/trazos': typeof TrazosRoute
  '/universo': typeof UniversoRoute
  '/vocabulario': typeof VocabularioRoute
  '/vowels': typeof VowelsRoute
  '/zoo': typeof ZooRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendario'
    | '/camino'
    | '/ciencia'
    | '/cocodrilo'
    | '/commands'
    | '/consonantes'
    | '/cueva'
    | '/cvc'
    | '/energia'
    | '/english'
    | '/evaluacion'
    | '/guatemala'
    | '/huerto'
    | '/inversas'
    | '/lenguaje'
    | '/matematicas'
    | '/moneda'
    | '/numeros100'
    | '/oraciones'
    | '/phonics'
    | '/pizzeria'
    | '/premios'
    | '/reserva'
    | '/restaurant'
    | '/romanos'
    | '/tecnicas'
    | '/torre'
    | '/trazos'
    | '/universo'
    | '/vocabulario'
    | '/vowels'
    | '/zoo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendario'
    | '/camino'
    | '/ciencia'
    | '/cocodrilo'
    | '/commands'
    | '/consonantes'
    | '/cueva'
    | '/cvc'
    | '/energia'
    | '/english'
    | '/evaluacion'
    | '/guatemala'
    | '/huerto'
    | '/inversas'
    | '/lenguaje'
    | '/matematicas'
    | '/moneda'
    | '/numeros100'
    | '/oraciones'
    | '/phonics'
    | '/pizzeria'
    | '/premios'
    | '/reserva'
    | '/restaurant'
    | '/romanos'
    | '/tecnicas'
    | '/torre'
    | '/trazos'
    | '/universo'
    | '/vocabulario'
    | '/vowels'
    | '/zoo'
  id:
    | '__root__'
    | '/'
    | '/calendario'
    | '/camino'
    | '/ciencia'
    | '/cocodrilo'
    | '/commands'
    | '/consonantes'
    | '/cueva'
    | '/cvc'
    | '/energia'
    | '/english'
    | '/evaluacion'
    | '/guatemala'
    | '/huerto'
    | '/inversas'
    | '/lenguaje'
    | '/matematicas'
    | '/moneda'
    | '/numeros100'
    | '/oraciones'
    | '/phonics'
    | '/pizzeria'
    | '/premios'
    | '/reserva'
    | '/restaurant'
    | '/romanos'
    | '/tecnicas'
    | '/torre'
    | '/trazos'
    | '/universo'
    | '/vocabulario'
    | '/vowels'
    | '/zoo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarioRoute: typeof CalendarioRoute
  CaminoRoute: typeof CaminoRoute
  CienciaRoute: typeof CienciaRoute
  CocodriloRoute: typeof CocodriloRoute
  CommandsRoute: typeof CommandsRoute
  ConsonantesRoute: typeof ConsonantesRoute
  CuevaRoute: typeof CuevaRoute
  CvcRoute: typeof CvcRoute
  EnergiaRoute: typeof EnergiaRoute
  EnglishRoute: typeof EnglishRoute
  EvaluacionRoute: typeof EvaluacionRoute
  GuatemalaRoute: typeof GuatemalaRoute
  HuertoRoute: typeof HuertoRoute
  InversasRoute: typeof InversasRoute
  LenguajeRoute: typeof LenguajeRoute
  MatematicasRoute: typeof MatematicasRoute
  MonedaRoute: typeof MonedaRoute
  Numeros100Route: typeof Numeros100Route
  OracionesRoute: typeof OracionesRoute
  PhonicsRoute: typeof PhonicsRoute
  PizzeriaRoute: typeof PizzeriaRoute
  PremiosRoute: typeof PremiosRoute
  ReservaRoute: typeof ReservaRoute
  RestaurantRoute: typeof RestaurantRoute
  RomanosRoute: typeof RomanosRoute
  TecnicasRoute: typeof TecnicasRoute
  TorreRoute: typeof TorreRoute
  TrazosRoute: typeof TrazosRoute
  UniversoRoute: typeof UniversoRoute
  VocabularioRoute: typeof VocabularioRoute
  VowelsRoute: typeof VowelsRoute
  ZooRoute: typeof ZooRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camino': {
      id: '/camino'
      path: '/camino'
      fullPath: '/camino'
      preLoaderRoute: typeof CaminoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ciencia': {
      id: '/ciencia'
      path: '/ciencia'
      fullPath: '/ciencia'
      preLoaderRoute: typeof CienciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cocodrilo': {
      id: '/cocodrilo'
      path: '/cocodrilo'
      fullPath: '/cocodrilo'
      preLoaderRoute: typeof CocodriloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commands': {
      id: '/commands'
      path: '/commands'
      fullPath: '/commands'
      preLoaderRoute: typeof CommandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consonantes': {
      id: '/consonantes'
      path: '/consonantes'
      fullPath: '/consonantes'
      preLoaderRoute: typeof ConsonantesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cueva': {
      id: '/cueva'
      path: '/cueva'
      fullPath: '/cueva'
      preLoaderRoute: typeof CuevaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cvc': {
      id: '/cvc'
      path: '/cvc'
      fullPath: '/cvc'
      preLoaderRoute: typeof CvcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/energia': {
      id: '/energia'
      path: '/energia'
      fullPath: '/energia'
      preLoaderRoute: typeof EnergiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/english': {
      id: '/english'
      path: '/english'
      fullPath: '/english'
      preLoaderRoute: typeof EnglishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluacion': {
      id: '/evaluacion'
      path: '/evaluacion'
      fullPath: '/evaluacion'
      preLoaderRoute: typeof EvaluacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guatemala': {
      id: '/guatemala'
      path: '/guatemala'
      fullPath: '/guatemala'
      preLoaderRoute: typeof GuatemalaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/huerto': {
      id: '/huerto'
      path: '/huerto'
      fullPath: '/huerto'
      preLoaderRoute: typeof HuertoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inversas': {
      id: '/inversas'
      path: '/inversas'
      fullPath: '/inversas'
      preLoaderRoute: typeof InversasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lenguaje': {
      id: '/lenguaje'
      path: '/lenguaje'
      fullPath: '/lenguaje'
      preLoaderRoute: typeof LenguajeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matematicas': {
      id: '/matematicas'
      path: '/matematicas'
      fullPath: '/matematicas'
      preLoaderRoute: typeof MatematicasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moneda': {
      id: '/moneda'
      path: '/moneda'
      fullPath: '/moneda'
      preLoaderRoute: typeof MonedaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/numeros100': {
      id: '/numeros100'
      path: '/numeros100'
      fullPath: '/numeros100'
      preLoaderRoute: typeof Numeros100RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oraciones': {
      id: '/oraciones'
      path: '/oraciones'
      fullPath: '/oraciones'
      preLoaderRoute: typeof OracionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phonics': {
      id: '/phonics'
      path: '/phonics'
      fullPath: '/phonics'
      preLoaderRoute: typeof PhonicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pizzeria': {
      id: '/pizzeria'
      path: '/pizzeria'
      fullPath: '/pizzeria'
      preLoaderRoute: typeof PizzeriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premios': {
      id: '/premios'
      path: '/premios'
      fullPath: '/premios'
      preLoaderRoute: typeof PremiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserva': {
      id: '/reserva'
      path: '/reserva'
      fullPath: '/reserva'
      preLoaderRoute: typeof ReservaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurant': {
      id: '/restaurant'
      path: '/restaurant'
      fullPath: '/restaurant'
      preLoaderRoute: typeof RestaurantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/romanos': {
      id: '/romanos'
      path: '/romanos'
      fullPath: '/romanos'
      preLoaderRoute: typeof RomanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tecnicas': {
      id: '/tecnicas'
      path: '/tecnicas'
      fullPath: '/tecnicas'
      preLoaderRoute: typeof TecnicasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/torre': {
      id: '/torre'
      path: '/torre'
      fullPath: '/torre'
      preLoaderRoute: typeof TorreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trazos': {
      id: '/trazos'
      path: '/trazos'
      fullPath: '/trazos'
      preLoaderRoute: typeof TrazosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universo': {
      id: '/universo'
      path: '/universo'
      fullPath: '/universo'
      preLoaderRoute: typeof UniversoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vocabulario': {
      id: '/vocabulario'
      path: '/vocabulario'
      fullPath: '/vocabulario'
      preLoaderRoute: typeof VocabularioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vowels': {
      id: '/vowels'
      path: '/vowels'
      fullPath: '/vowels'
      preLoaderRoute: typeof VowelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zoo': {
      id: '/zoo'
      path: '/zoo'
      fullPath: '/zoo'
      preLoaderRoute: typeof ZooRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarioRoute: CalendarioRoute,
  CaminoRoute: CaminoRoute,
  CienciaRoute: CienciaRoute,
  CocodriloRoute: CocodriloRoute,
  CommandsRoute: CommandsRoute,
  ConsonantesRoute: ConsonantesRoute,
  CuevaRoute: CuevaRoute,
  CvcRoute: CvcRoute,
  EnergiaRoute: EnergiaRoute,
  EnglishRoute: EnglishRoute,
  EvaluacionRoute: EvaluacionRoute,
  GuatemalaRoute: GuatemalaRoute,
  HuertoRoute: HuertoRoute,
  InversasRoute: InversasRoute,
  LenguajeRoute: LenguajeRoute,
  MatematicasRoute: MatematicasRoute,
  MonedaRoute: MonedaRoute,
  Numeros100Route: Numeros100Route,
  OracionesRoute: OracionesRoute,
  PhonicsRoute: PhonicsRoute,
  PizzeriaRoute: PizzeriaRoute,
  PremiosRoute: PremiosRoute,
  ReservaRoute: ReservaRoute,
  RestaurantRoute: RestaurantRoute,
  RomanosRoute: RomanosRoute,
  TecnicasRoute: TecnicasRoute,
  TorreRoute: TorreRoute,
  TrazosRoute: TrazosRoute,
  UniversoRoute: UniversoRoute,
  VocabularioRoute: VocabularioRoute,
  VowelsRoute: VowelsRoute,
  ZooRoute: ZooRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
